name: run daily
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout codes
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      
      - name: install libraries
        run: |
          pip install -r requirements.txt
      
      - name: run main.py
        env:
          ck: ${{ secrets.CK }}
          cs: ${{ secrets.CS }}
          at: ${{ secrets.AT }}
          ats: ${{ secrets.ATS }}
        run: python ./scripts/main.py